import Link from 'next/link'

import Layout from '../components/Layout'
import { withData } from '../utils/withData'

export default function Index({ posts }) {
  return (
    <Layout>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{' '}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {posts.map((post) => (
          <li key={post.filePath}>
            <Link
              href={`/${post.filePath}`}
            >
              <a>{post.data.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </Layout>
  )
}

export const getStaticProps = withData(
  ({ data }) => () => {
    const posts = Object.keys(data).map((filePath) => ({
      filePath,
      ...data[filePath],
    }))

    return {
      props: {
        posts,
      },
    }
  },
  ['posts']
)
